/* Generated By:JavaCC: Do not edit this line. YalTreeConstants.java Version 5.0 */
public interface YalTreeConstants
{
  public int JJTROOT = 0;
  public int JJTMODULE = 1;
  public int JJTDECLARATION = 2;
  public int JJTINTEGER = 3;
  public int JJTFUNCTION = 4;
  public int JJTFUNCTIONRETURN = 5;
  public int JJTVARLIST = 6;
  public int JJTELEMENT = 7;
  public int JJTBODY = 8;
  public int JJTVOID = 9;
  public int JJTASSIGN = 10;
  public int JJTOPERATION = 11;
  public int JJTARRAYSIZE = 12;
  public int JJTCONDITION = 13;
  public int JJTWHILE = 14;
  public int JJTIF = 15;
  public int JJTCALL = 16;
  public int JJTARGUMENTLIST = 17;
  public int JJTARGUMENT = 18;
  public int JJTACCESS = 19;
  public int JJTINDEX = 20;


  public String[] jjtNodeName = {
    "Root",
    "Module",
    "Declaration",
    "Integer",
    "Function",
    "FunctionReturn",
    "Varlist",
    "Element",
    "Body",
    "void",
    "Assign",
    "Operation",
    "ArraySize",
    "Condition",
    "While",
    "If",
    "Call",
    "ArgumentList",
    "Argument",
    "Access",
    "Index",
  };
}
/* JavaCC - OriginalChecksum=1807c9a2b734b7641dc8ecfb2bc5ee06 (do not edit this line) */
